---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-cluster-side
  namespace: dummy
spec:
  project: default
  source:
    directory:
      recurse: false
    path: sealed-secrets-cluster-side/overlays/sugardon01
    repoURL: https://github.com/sugardon-org/kubernetes-secret
    targetRevision: main
  destination:
    namespace: sealed-secrets
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-client-side
  namespace: dummy
spec:
  project: default
  source:
    directory:
      recurse: true
    path: sealed-secrets-client-side/sugardon01
    repoURL: https://github.com/sugardon-org/kubernetes-secret
    targetRevision: main
  destination:
    namespace: sealed-secrets
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
