apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test-secret
  namespace: default
spec:
  encryptedData:
    test: AgClyRiGvtGBUYwV4RN0y8gpxd6HZgbgKTqjy3qYpOfYynEI7dRHcn5w4obHZr3T6XdIK0pMizfrv1NGjzf980Z7j/Pp8earGUh5PkLLu/SLK+nFxQrvt7NGQNxUWiez4Wu/dajgLGgN93NKNn4LujPEdrE0reV08d96nqF4ozu8jVdPehBcWUYWT7xMjzQ1c/oCDFcoDhMiEsdOJX12i1ZWvfGCGmcqFUwr7BB3M6wzgBQZG//n4XIngt8id/iU0oeqlh347ByTft2OLCDyNrIh59QVQ6nB4e5xuR8bRfnLgZPNr4aPRlhyp1B8mIRaWYaq9pJT/Ps5Lra7fMKU9dLFKaI0NsdkMMdrKaGSYajeey+6w8Xq84wRB6c8xmjoFdUrV7zkdzDbkRho9WvH+JLgw7fpxN3u/ltjZpbvTV3bxyRYVyVAnSXhMtwNLEv2HF8RrhLnPV79ohzgLpYuCLUOAJPMJkdIq5FiTCHwhCpcV684YVF+3gBSEE68/zq8U9yzaj3fs95KLoCaLoN2XVCobLiKDAlZzlqkBXH4OOb3HOVZ3IRMyjyGjutTOuT1QOwN4cF/suYYCBPCJJGNmEpXvngJnBbXIT2ccdkR7AqYwcPp/N/faK+HLBXw3aFZbdabBN5GNRj/npgDfST+6CRknqseUYAjoaubdMDPc3AnroEFQ7iJxNSnvfQBT47U3KZNY4I1xg==
  template:
    metadata:
      creationTimestamp: null
      name: test-secret
      namespace: default
    type: Opaque

