apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sugardon-dockerhub-secret
  namespace: tekton-cicd
spec:
  encryptedData:
    .dockerconfigjsonn: AgCCdllFPaIGUwd5TRxubXi8uoEzl6Ya1t24+xN8UbH/ufDcSc9K8wNuu0i1RUXQ1iGgbby4rZJatiiQ35iMDJMeiGAlVf5xNnk9vO/TJkCsOub5VW7NKsQ2i2DSW04PjurbmqyYSqs9YiVcVnRBphbuWccm8nh8IUtOn1NUBsIUepgg7/u+DK10G2DBYV5oz9E9827Goq/nzqK6/7tGVJB73C1hGwbqX4I19Pw6vHcctvwkNysRPu9VgtE3mfWH6pJQcZ/xniy7YQI6zZmmV0pBoDf+dhiGvqpGxRdQI9jRj5C3tU/HEjAVOeQQFawqKKVza01++Cw3vhad/DJm53+imKIWbErvGOPCeXOcpcjLUaecgIolG4hibGEphT84CwWDKsyjCAQzSDQ2GhSpMKrY+VdnTMAms1Np0QIRHDjyLYZ0ABOSFG1rlWd1N3FLHxsyhixKZTLOZVUeroGgW91nS7x+cZqwXkED1FzVy8q2xNcdHT3tjazxd+SPw6C0rlvYa2HmyvaMLu/53OSx4715Ibxa/eKr3vfwm92X6ns7A/x1RgeDlpJkS9qOFrtaGvfp8EyYe6RCFaNrBBI07QfuNFT275oJJm2JD3Gwh6DC3McLuOVpdBdPOMpXnwAb4SUBcslL7SnKDH3nC/Gi4BKb2pWPrr2d1urEoatatLL+kOgpfUgT2jMJPduvJojqiNYTzICZspHahNIeFEdqbVpEMefX7ofyoMxy2gwj5WxyH0KeOVnyoVVCmX2E+TWEFzhNCbMQmmAMbBePk+yN2TZmvLj8cl5BbOLSzcNSvCd9iZg5z+XxAJQx26d7FFS8Uz6iajMSJE/1aUGDpt1CTp8nfJksbQPL3R6B7JuHxsR6yww=
  template:
    metadata:
      creationTimestamp: null
      name: sugardon-dockerhub-secret
      namespace: tekton-cicd
    type: kubernetes.io/dockerconfigjson

